name: Test Files

on:
  push:
    tags: 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: |
        ls
        pwd
        echo "${{ github.workspace }}"
